/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempcontrolia;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author igorb
 */
public final class FrameControl extends javax.swing.JFrame {
    /**
     * Creates new form FrameControl
     */
    public static Grafico grafico;
    
        
    public FrameControl()  {
        initComponents();
        setResizable(false); 
        
        /*Objeto que gera os graficos*/
        grafico = new Grafico();
        
        
        /*PLOTANDO PRIMEIRO GRAFICO*/
        grafico.dsExterna = new DefaultCategoryDataset();
        pTemExterna.add(grafico.geraGraficoTempExterna(grafico.dsExterna,"temperatura Externa"));
        
        /*PLOTANDO SEGUNDO GRAFICO*/
        grafico.dsInterna = new DefaultCategoryDataset();
        grafico.dsInterna.addValue(40.5, "temperatura", "t1");
        grafico.dsInterna.addValue(38.2, "temperatura", "t2");
        grafico.dsInterna.addValue(37.3, "temperatura", "t3");
        grafico.dsInterna.addValue(31.5, "temperatura", "t4");
        pTempInterna.add(grafico.geraGraficoTempInterna(grafico.dsInterna,"Temperatura Interna"));
        
        
        ImageIcon icon = new ImageIcon("C:\\Users\\igorb\\Documents\\NetBeansProjects\\TempControlIA\\src\\tempcontrolia\\images\\termometro.png");
        jLabelTerm.setIcon(icon);
        jLabelTerm1.setIcon(icon);
        
        setTemperaturaFicticia();
    } 
    
    public static void setTemperaturaFicticia(){
         Random gerador = new Random();
         new Thread(){
          @Override
          public void run() {   
              while(true){
                  try {
                    Thread.sleep(2000); 
                  } catch (InterruptedException ex) {
                    Logger.getLogger(FrameControl.class.getName()).log(Level.SEVERE, null, ex);
                  }
              
                  if (grafico.dsExterna.getColumnCount() >= 4)
                       grafico.dsExterna.removeColumn(0);
                  
                  grafico.dsExterna.addValue((gerador.nextDouble() * 35)+10,"temperatura","t"+grafico.idTemp);
                  grafico.plotTempExterna.setDataset(grafico.dsExterna);          
                  grafico.idTemp++;
              }
           }
        }.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pTemExterna = new javax.swing.JPanel();
        jLabelTerm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelArCond = new javax.swing.JLabel();
        pTempInterna = new javax.swing.JPanel();
        jLabelTerm1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 720));

        pTemExterna.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pTemExternaLayout = new javax.swing.GroupLayout(pTemExterna);
        pTemExterna.setLayout(pTemExternaLayout);
        pTemExternaLayout.setHorizontalGroup(
            pTemExternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTemExternaLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabelTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTemExternaLayout.setVerticalGroup(
            pTemExternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTemExternaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabelTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelArCond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tempcontrolia/ar-cond.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabelArCond)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelArCond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        pTempInterna.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pTempInternaLayout = new javax.swing.GroupLayout(pTempInterna);
        pTempInterna.setLayout(pTempInternaLayout);
        pTempInternaLayout.setHorizontalGroup(
            pTempInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTempInternaLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabelTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTempInternaLayout.setVerticalGroup(
            pTempInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTempInternaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTemExterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pTempInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pTemExterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTempInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new FrameControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelArCond;
    private javax.swing.JLabel jLabelTerm;
    private javax.swing.JLabel jLabelTerm1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pTemExterna;
    private javax.swing.JPanel pTempInterna;
    // End of variables declaration//GEN-END:variables
}
