/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.Chart;
import models.TemperatureController;

/**
 *
 * @author igorb
 */
public class FrameFuzzifyChart extends javax.swing.JFrame {

    /**
     * Creates new form FrameFuzzifyChart
     */
    public static TemperatureController tempControl;
    
    public FrameFuzzifyChart(TemperatureController tempControl) {
        initComponents();
        setResizable(false);
        
        this.tempControl = tempControl;
        plotCharts();
    }
    
    /*Plotando os graficos na tela*/
    public void plotCharts(){
        Chart chart = new Chart();
        jPanelTempInterna.add(chart.getChartInternTemp(tempControl.getFb().getVariable("temperaturainterna")));
        jPanelTamanhoSala.add(chart.getChartRoomDimensions(tempControl.getFb().getVariable("tamanhosala")));
        jPanelOcupacaoSala.add(chart.getChartRoomOcupation(tempControl.getFb().getVariable("ocupacaosala")));
        jPanelDefuzzy.add(chart.getChartDefuzzify(tempControl.getFb().getVariable("ajusteideal")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTempInterna = new javax.swing.JPanel();
        jPanelOcupacaoSala = new javax.swing.JPanel();
        jPanelTamanhoSala = new javax.swing.JPanel();
        jPanelDefuzzy = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTempInterna.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTempInternaLayout = new javax.swing.GroupLayout(jPanelTempInterna);
        jPanelTempInterna.setLayout(jPanelTempInternaLayout);
        jPanelTempInternaLayout.setHorizontalGroup(
            jPanelTempInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTempInternaLayout.setVerticalGroup(
            jPanelTempInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelOcupacaoSala.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelOcupacaoSalaLayout = new javax.swing.GroupLayout(jPanelOcupacaoSala);
        jPanelOcupacaoSala.setLayout(jPanelOcupacaoSalaLayout);
        jPanelOcupacaoSalaLayout.setHorizontalGroup(
            jPanelOcupacaoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        jPanelOcupacaoSalaLayout.setVerticalGroup(
            jPanelOcupacaoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanelTamanhoSala.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTamanhoSalaLayout = new javax.swing.GroupLayout(jPanelTamanhoSala);
        jPanelTamanhoSala.setLayout(jPanelTamanhoSalaLayout);
        jPanelTamanhoSalaLayout.setHorizontalGroup(
            jPanelTamanhoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanelTamanhoSalaLayout.setVerticalGroup(
            jPanelTamanhoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanelDefuzzy.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDefuzzyLayout = new javax.swing.GroupLayout(jPanelDefuzzy);
        jPanelDefuzzy.setLayout(jPanelDefuzzyLayout);
        jPanelDefuzzyLayout.setHorizontalGroup(
            jPanelDefuzzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDefuzzyLayout.setVerticalGroup(
            jPanelDefuzzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelTamanhoSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTempInterna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOcupacaoSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDefuzzy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelOcupacaoSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTempInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTamanhoSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDefuzzy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFuzzifyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFuzzifyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFuzzifyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFuzzifyChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFuzzifyChart(tempControl).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDefuzzy;
    private javax.swing.JPanel jPanelOcupacaoSala;
    private javax.swing.JPanel jPanelTamanhoSala;
    private javax.swing.JPanel jPanelTempInterna;
    // End of variables declaration//GEN-END:variables
}
